### ISSUE TITLE
关于单端口多用户这种方式，大佬有没有好的思路？

### ISSUE THREAD

**Issue by mokitoo** [TongxiJi/shadowsocks-java#13]
如题，java在内存方面没有任何优势，如果能支持单端口多用户的话就可以解决这种问题
大佬在这个方面有啥好的思路么？

**Comment by TongxiJi** [comment]
https://github.com/TongxiJi/shadowsocks-java/blob/master/src/main/java/cn/wowspeeder/ss/obfs/impl/HttpSimpleHandler.java

支持了ssr的http-simple混淆头方式, 为所欲为吧.

**Comment by mokitoo** [comment]
看了下ssr的源码，好像是通过md5加密后的协议参数来区分不同的用户的
如果是原版ss的话，因为没有协议参数这种东西，其实直接通过密码也能区分用户
现在的问题是绑定一个端口以后，如果去给不同的用户初始化ChannelInitializer

**Comment by TongxiJi** [comment]
ss原始单端口多用户没可能了.  我之前也想过。。。

**Comment by mokitoo** [comment]
你觉得没可能的原因是啥…
