### ISSUE TITLE
开启http_simple情况下的一个bug

### ISSUE THREAD

**Issue by mokitoo** [TongxiJi/shadowsocks-java#16]
### **问题：**
开启http_simple情况下，SSCipherCodec 的入站的时候，最后会收到一个LastHttpContent的msg，
如下图所示，按照现在的代码就直接抛出exception了
<img src="http://ww1.sinaimg.cn/large/006TlzFEly1g36tic3fa1j30qe071wfb.jpg"/>

查了下网上说是这么个玩意
<img src="http://ww1.sinaimg.cn/large/006TlzFEly1g36tkdu9xaj30oo0hd776.jpg"/>

### **解决方案：**
我是在SSCipherCodec类  decode的时候，加了个判断直接把它return掉了，不知道这样处理对不对啊？
`else if (msg instanceof LastHttpContent){
            return;
        }`

**Comment by TongxiJi** [comment]
什么客户端, 客户端开启http-simple混淆了吗?

**Comment by TongxiJi** [comment]
你那边ssr客户端还是不能用?

**Comment by mokitoo** [comment]
SSR的客户端，开启了http-simple。
可以用，只不过不停有上面那个报错出来

**Comment by mokitoo** [comment]
你的服务端没有收到这个 LastHttpContent 消息吗？

**Comment by TongxiJi** [comment]
https://github.com/TongxiJi/shadowsocks-java/commit/5adb6889764d4f3224f8ba6ef5beaf5853bcdc62

提交了，netty的http请求默认分成两段来处理了。 HttpSimpleHandler只需要改下这个就行了。

**Comment by TongxiJi** [comment]
提交了，netty的http请求默认分成两段来处理了。 HttpSimpleHandler只需要改下这个就行了。
https://github.com/TongxiJi/shadowsocks-java/commit/eb0faa27eee1b27200c2c546ef2c711fa8e16f89

**Comment by mokitoo** [comment]
好的，感谢，你有telegram嘛？ 可以方便交流
