### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by l42111996** [TongxiJi/shadowsocks-java#21]
我看百度上面shadowsocks协议的有握手阶段，会发送账号密码等信息 ，握手之后进行请求，但是我debug始终没有收到握手的协议。这个可能是什么原因？

**Comment by l42111996** [comment]
看了一遍SSLocal代码，应该是手机连接->socks5本地监听转ss协议发送给服务器->服务器接收ss协议发给对应的网站
是这样子吗？ 我把ss协议和socks5协议弄混淆了

**Comment by tomzh0u** [comment]
2楼就是这个逻辑
